[package]
name = "your-username/template-plugin"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

[dependencies]
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
